services:
  mysql:
    image: mariadb:10-focal
    command: '--default-authentication-plugin=mysql_native_password'
    restart: always
    volumes:
    - db-data:/var/lib/mysql
    environment:
    - MARIADB_USER=app
    - MARIADB_PASSWORD=app
    - MARIADB_ROOT_PASSWORD=root
    - MARIADB_DATABASE=app
    expose:
    - 3306

  app:
    build:
      context: app
    restart: always
    environment:
    - MYSQL_DATABASE_USER=app
    - MYSQL_DATABASE_PASSWORD=app
    - MYSQL_DATABASE_DB=app
    - MYSQL_DATABASE_HOST=mysql
    - MYSQL_DATABASE_PORT=3306
    ports:
    - 5000:5000

volumes:
  db-data:
