apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- userapi.yaml

images:
- name: localhost:30003/userapi:latest
  newName: localhost:30003/userapi
  newTag: NEW_USERAPI_TAG

- name: nginx:latest
  newName: nginx
  newTag: "1.25"
